2023-11-28 17:05:54,049 INFO    MainThread:134728 [wandb_setup.py:_flush():76] Current SDK version is 0.16.0
2023-11-28 17:05:54,049 INFO    MainThread:134728 [wandb_setup.py:_flush():76] Configure stats pid to 134728
2023-11-28 17:05:54,049 INFO    MainThread:134728 [wandb_setup.py:_flush():76] Loading settings from /home/alberto/.config/wandb/settings
2023-11-28 17:05:54,049 INFO    MainThread:134728 [wandb_setup.py:_flush():76] Loading settings from /home/alberto/lab/qentropy_projects/qrage/wandb/settings
2023-11-28 17:05:54,049 INFO    MainThread:134728 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-11-28 17:05:54,049 INFO    MainThread:134728 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-11-28 17:05:54,049 INFO    MainThread:134728 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'app.py', 'program_abspath': '/home/alberto/lab/qentropy_projects/qrage/app.py', 'program': '/home/alberto/lab/qentropy_projects/qrage/app.py'}
2023-11-28 17:05:54,049 INFO    MainThread:134728 [wandb_init.py:_log_setup():524] Logging user logs to /home/alberto/lab/qentropy_projects/qrage/wandb/run-20231128_170554-i2jcte7a/logs/debug.log
2023-11-28 17:05:54,049 INFO    MainThread:134728 [wandb_init.py:_log_setup():525] Logging internal logs to /home/alberto/lab/qentropy_projects/qrage/wandb/run-20231128_170554-i2jcte7a/logs/debug-internal.log
2023-11-28 17:05:54,049 INFO    MainThread:134728 [wandb_init.py:init():564] calling init triggers
2023-11-28 17:05:54,049 INFO    MainThread:134728 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2023-11-28 17:05:54,049 INFO    MainThread:134728 [wandb_init.py:init():614] starting backend
2023-11-28 17:05:54,049 INFO    MainThread:134728 [wandb_init.py:init():618] setting up manager
2023-11-28 17:05:54,050 INFO    MainThread:134728 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-11-28 17:05:54,051 INFO    MainThread:134728 [wandb_init.py:init():624] backend started and connected
2023-11-28 17:05:54,053 INFO    MainThread:134728 [wandb_init.py:init():716] updated telemetry
2023-11-28 17:05:54,056 INFO    MainThread:134728 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2023-11-28 17:05:54,697 INFO    MainThread:134728 [wandb_run.py:_on_init():2254] communicating current version
2023-11-28 17:05:54,846 INFO    MainThread:134728 [wandb_run.py:_on_init():2263] got version response 
2023-11-28 17:05:54,847 INFO    MainThread:134728 [wandb_init.py:init():800] starting run threads in backend
2023-11-28 17:05:54,932 INFO    MainThread:134728 [wandb_run.py:_console_start():2233] atexit reg
2023-11-28 17:05:54,932 INFO    MainThread:134728 [wandb_run.py:_redirect():2088] redirect: wrap_raw
2023-11-28 17:05:54,933 INFO    MainThread:134728 [wandb_run.py:_redirect():2153] Wrapping output streams.
2023-11-28 17:05:54,933 INFO    MainThread:134728 [wandb_run.py:_redirect():2178] Redirects installed.
2023-11-28 17:05:54,935 INFO    MainThread:134728 [wandb_init.py:init():841] run started, returning control to user process
2023-11-28 17:05:54,936 ERROR   MainThread:134728 [util.py:get_module():267] Error importing optional module cohere
Traceback (most recent call last):
  File "/home/alberto/lab/.venv/lib/python3.11/site-packages/wandb/util.py", line 260, in get_module
    return import_module(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'cohere'
2023-11-28 17:06:00,848 WARNING MsgRouterThr:134728 [router.py:message_loop():77] message_loop has been closed
